### PR TITLE
Http2live 🚀

### LINKED ISSUE #2: PHP to static site
Hi @serrynaimo 

I'm trying to convert the site to static files so it can be hosted on the [http2.live](https://http2.live) CDN.

1. Why is there `/index.html` and `/index.php`?
1. What does this PHP statement do that `new Date()` couldn't?
   https://github.com/serrynaimo/2018.jsconf.asia/blob/00dcaac6a47f190637dc3f41abfa2c6378c35aef/index.php#L131
1. Can we use feature detection instead of user agent sniffing?
   https://github.com/serrynaimo/2018.jsconf.asia/blob/00dcaac6a47f190637dc3f41abfa2c6378c35aef/lunch/index.php#L14
1. Consider adding `.DS_Store` to a global `.gitignore` file on your system. (I'll clean them up here in the PR.)

### PR DESCRIPTION
**Pull request by sebdeckers**
I kept the commit history visible to show that none of the site content was modified. Only things I removed were traces of PHP and the legacy "lunch" minisite. Closes #2 

For your convenience I've deployed a preview of the static site to: https://2018-jsconf-asia.http2.live

You can sign up and create an account to control the production deployment yourself. Run `npx @http2/live signup` to register an account. (You need to have 

To set the production domain name as `2018.jsconf.asia` you'll need to point your CNAME record at `http2.live`. The domain must be set before the deployment, otherwise LetsEncrypt will not issue the certificate (this happens automatically during deployment). Also update the `domain` property in [`http2server.conf.js`](https://github.com/sebdeckers/2018.jsconf.asia/blob/1dce6112edd705730f133249b2aef9d79cfcf7a9/http2server.production.conf.js#L4) to `2018.jsconf.asia`.

## Result

- Hosted in Singapore 🇸🇬 using Node.js 🌈
- Secure hosting with a proper TLS certificate. Uses ECC P-256 for better efficiency & higher security than RSA 2048.
- HTTP/2 Server Push to eliminate round trips, without the hassle of Webpack.

screen shot 2017-10-22 at 5 45 59 pm

### CODE REVIEW

**Comment by serrynaimo** [comment]
Cool, thanks! Looks pretty good. Will I be able to bring the /lunch site back later? I'll need it.
I'll also want to find a solution to the server-time before I can make that change.

**Comment by sebdeckers** [comment]
Okay, understood. Let me restore the `/lunch` content for now. I'll set up the manifest so those files are pushed separately.

Hmm, I have a sneaky idea for using server push to get the current time from the webserver. We want to avoid a slow async call to some time API service. Gimme some time (pun intended).

**Comment by sebdeckers** [comment]
@serrynaimo Got it working. Take a look at 1b2fde9 for the magic. 😎

**Comment by serrynaimo** [comment]
thanks for this :) in the mean-time I'm off for some

npm i *snooze*....

**Pull request merged**
